languageCode = "en-us"
baseurl = "https://ericchiang.github.io/"
title = "posts"
theme = "xmin"
[services]
  [services.googleAnalytics]
    ID = "G-YR9ZQCMH4S"

[author]
    name = "Eric Chiang"
    github = "ericchiang"
    twitter = "erchiang"

[[menu.main]]
    name = "1"
    identifier = "posts"
    url = "/"

[[menu.main]]
    name = "2"
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "2"
    identifier = "license"
    url = "/license/"
