languageCode = "en-us"
baseurl = "https://ericchiang.github.io/"
title = "Eric Chiang"
theme = "xmin"
[services]
  [services.googleAnalytics]
    ID = "G-YR9ZQCMH4S"

[[params.author]]
    name = "Eric Chiang"

[[menu.main]]
    name = "1"
    identifier = "Eric Chiang"
    url = "/about/"

[[menu.main]]
    name = "2"
    identifier = "posts"
    url = "/"

[[menu.main]]
    name = "3"
    identifier = "rss"
    url = "/index.xml"

[[menu.main]]
    name = "4"
    identifier = "license"
    url = "/license/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
